//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPruebaFARSIMAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbColaboradores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbColaboradores()
        {
            this.tbViajesColaborador = new HashSet<tbViajesColaborador>();
        }
    
        public int col_Id { get; set; }
        public string col_Nombre { get; set; }
        public string col_Apellido { get; set; }
        public int col_UsuarioCrea { get; set; }
        public System.DateTime col_FechaCrea { get; set; }
        public Nullable<decimal> col_DistanciaSucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbViajesColaborador> tbViajesColaborador { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
