//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPruebaFARSIMAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrecioKilometro
    {
        public int pkm_id { get; set; }
        public Nullable<decimal> pkm_Cantidad { get; set; }
        public Nullable<decimal> pkm_Precio { get; set; }
    }
}
