//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPruebaFARSIMAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSucursales
    {
        public int suc_Id { get; set; }
        public string suc_Nombre { get; set; }
        public int suc_UsuarioCrea { get; set; }
        public System.DateTime suc_FechaCrea { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
